org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
mod_id=functional_storage_js
mod_name=Functional Storage for KubeJS
mod_license=GNU LGPL 3.0
mod_version=1.2
mod_group_id=dev.celestiacraft
mod_authors=TeamNebula
mod_description=
#
jei_version=15.20.0.129